logging:
  level:
    org.apache.http: off
    com.gargoylesoftware: off

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/web_scraper
    username: root
    password: mypassword

amazon:
  username: ${AMAZON_USERNAME:username}
  password: ${AMAZON_PASSWORD:password}
  url: https://www.amazon.com/
  historyUrl: https://www.amazon.com/gp/your-account/order-history?opt=ab&digitalOrders=1&unifiedOrders=1&returnTo=&orderFilter=
  productUrl: https://www.amazon.com/gp/product/

  crawling:
    # Front page button
    loginButton: "#nav-link-accountList"

    # Login page
    emailInput: "input#ap_email"
    continueInput: "input#continue"
    passwordInput: "input#ap_password"
    submitButton: "input#signInSubmit"

    # Purchase history page
    orderDate: "div.order-info > div > div > div > div:nth-of-type(1) > div > div:nth-of-type(1) > div:nth-of-type(2) > span"
    totalAmount: "div.order-info > div > div > div > div:nth-of-type(1) > div > div:nth-of-type(2) > div:nth-of-type(2) > span"
    orderNumber: "div.order-info > div > div > div > div:nth-of-type(2) > div:nth-of-type(1) > span:nth-of-type(2)"
    deliveryStatus: "div.shipment   > div > div:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(2) > span:nth-of-type(1)"

    ordersBox: "#ordersContainer > div.order"
    productsBox: "div.shipment > div > div > div > div:nth-of-type(1) > div > div.a-fixed-left-grid"

    # the following css selectors are inside products_box
    productAnchor: "div > div:nth-of-type(2) > div:nth-of-type(1) > a"
    productDistributor: "span.a-color-secondary"
    unitPrice: "span.a-color-price"
    productQuantity: "span.item-view-qty"

    nextPage: "#ordersContainer > div.a-row > div > ul > li.a-last > a"

    # Product detail page
    productDetail:
      productInfoTable: "#productDetails_detailBullets_sections1"
      salesRank: "#SalesRank"
      price: "#priceblock_ourprice"
      name: "#productTitle"
