resources:
  - scraper-db-deployment.yaml
  - scraper-db-service.yaml
  - scraper-solr-deployment.yaml
  - scraper-solr-service.yaml
  - scraper-app-deployment.yaml
  - scraper-app-service.yaml
  - scraper-web-deployment.yaml
  - scraper-web-service.yaml
