apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.local.yml convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: scraper-solr
  name: scraper-solr
spec:
  ports:
  - name: "9983"
    port: 9983
    targetPort: 8983
  selector:
    io.kompose.service: scraper-solr
status:
  loadBalancer: {}
