apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scraper-change-detection-check-cronjob
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: scraper-change-detection-check-cronjob
        spec:
          restartPolicy: OnFailure
          containers:
          - args:
            - bash
            - -c
            - sleep 10; cd /root/scraper/; java -jar web-scraper-server-*.jar --batch=change_detection_check --spring.config.location=file:application.yaml > logs_change_detection_check.log
            env:
            - name: SCRAPER_DB_PORT_3306_TCP_ADDR
              value: scraper-db
            image: tc3jp/scraper-app:dev1.0
            name: scraper-change-detection-check-cronjob
