version: '3'
services:
  scraper-app:
    image: scraper:0.0.1
    build: ./scraper/build
    container_name: "scraper-app"
    environment:
      SCRAPER_DB_PORT_3306_TCP_ADDR: 10.1.1.2
      AMAZON_USERNAME: jqp@example.com
      AMAZON_PASSWORD: password
    links:
      - scraper-db
    networks:
      scraper_net:
        ipv4_address: 10.1.1.1
    depends_on:
      - scraper-db
    volumes:
      - "../build/docker/scraper/logs:/root/scraper/logs"
    #  - "../build/dl-html:/scraper/dl-html"
    #  - "../build/log:/var/log/scraper"
    tty: true

  scraper-db:
    image: mysql:latest
    container_name: "scraper-db"
    ports:
      - 3306:3306
    networks:
      scraper_net:
        ipv4_address: 10.1.1.2
    environment:
      MYSQL_DATABASE: web_scraper
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: mypassword

networks:
  scraper_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
