version: '3'
services:

  scraper-db:
    build: ./mysql/build
    image: scraper-db:latest
    container_name: "scraper-db"
    ports:
      - 3306:3306
    networks:
      scraper_net:
        ipv4_address: 10.1.1.3
    environment:
      MYSQL_DATABASE: web_scraper
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: mypassword
    volumes:
      - "./mysql/build/conf.d:/etc/mysql/conf.d"
      - "./mysql/build/initdb.d:/root/mysql/initdb.d"
      - "./local-data/mysql/data:/var/lib/mysql"
      - "./local-data/mysql/logs:/var/log/mysql"
    privileged: true

networks:
  scraper_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
